// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalLMS.Models
{
    public partial class Assignments
    {
        public int AssignmentId { get; set; }
        public string AssignmentName { get; set; }
        public int CourseId { get; set; }
        public DateTime? DueDate { get; set; }
    }
}