// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalLMS.Models
{
    public partial class Courses
    {
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public string Course { get; set; }
        public int InstructorId { get; set; }
    }
}