// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalLMS.Models
{
    public partial class Instructors
    {
        public int InstructorId { get; set; }
        public string InstructorFirstname { get; set; }
        public string InstructorLastname { get; set; }
    }
}