// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalLMS.Models
{
    public partial class Registration
    {
        public int RegistrationId { get; set; }
        public int CourseId { get; set; }
        public int StudentId { get; set; }
    }
}