// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using FinalLMS.Models;

#nullable disable

namespace FinalLMS.Data
{
    public partial class FinalLMSContext : DbContext
    {
        public FinalLMSContext()
        {
        }

        public FinalLMSContext(DbContextOptions<FinalLMSContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Assignments> Assignments { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Instructors> Instructors { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<Students> Students { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Assignments>(entity =>
            {
                entity.HasKey(e => e.AssignmentId)
                    .HasName("PK__Assignme__9E0E9F2FCD5A58A2");

                entity.Property(e => e.AssignmentId).HasColumnName("Assignment_Id");

                entity.Property(e => e.AssignmentName)
                    .HasMaxLength(28)
                    .IsUnicode(false)
                    .HasColumnName("Assignment_Name");

                entity.Property(e => e.CourseId).HasColumnName("Course_Id");

                entity.Property(e => e.DueDate)
                    .HasColumnType("datetime")
                    .HasColumnName("Due_Date");
            });

            modelBuilder.Entity<Courses>(entity =>
            {
                entity.HasKey(e => e.CourseId)
                    .HasName("PK__Courses__37E005DB524B6353");

                entity.Property(e => e.CourseId).HasColumnName("Course_Id");

                entity.Property(e => e.Course)
                    .HasMaxLength(28)
                    .IsUnicode(false);

                entity.Property(e => e.CourseName)
                    .HasMaxLength(28)
                    .IsUnicode(false)
                    .HasColumnName("Course_Name");

                entity.Property(e => e.InstructorId).HasColumnName("Instructor_Id");
            });

            modelBuilder.Entity<Instructors>(entity =>
            {
                entity.HasKey(e => e.InstructorId)
                    .HasName("PK__Instruct__DD4B9AEA9813785B");

                entity.Property(e => e.InstructorId).HasColumnName("Instructor_Id");

                entity.Property(e => e.InstructorFirstname)
                    .HasMaxLength(28)
                    .IsUnicode(false)
                    .HasColumnName("Instructor_Firstname")
                    .IsFixedLength(true);

                entity.Property(e => e.InstructorLastname)
                    .HasMaxLength(28)
                    .IsUnicode(false)
                    .HasColumnName("Instructor_Lastname")
                    .IsFixedLength(true);
            });

            modelBuilder.Entity<Registration>(entity =>
            {
                entity.Property(e => e.RegistrationId).HasColumnName("Registration_Id");

                entity.Property(e => e.CourseId).HasColumnName("Course_Id");

                entity.Property(e => e.StudentId).HasColumnName("Student_Id");
            });

            modelBuilder.Entity<Students>(entity =>
            {
                entity.HasKey(e => e.StudentId)
                    .HasName("PK__Students__A2F4E98CA5BA9D90");

                entity.Property(e => e.StudentId).HasColumnName("Student_Id");

                entity.Property(e => e.StudentFirstname)
                    .HasMaxLength(28)
                    .IsUnicode(false)
                    .HasColumnName("Student_Firstname")
                    .IsFixedLength(true);

                entity.Property(e => e.StudentLastname)
                    .HasMaxLength(28)
                    .IsUnicode(false)
                    .HasColumnName("Student_Lastname")
                    .IsFixedLength(true);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}